Submit of Kangaroo model
alibaba/EasyNLP pull request #171
Opened 2022-07-31 05:51 UTC by RheaRia

2022-07-31 05:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyNLP?pullRequest=171) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyNLP?pullRequest=171) before we can accept your contribution.<br/><hr/>**Rhea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyNLP?pullRequest=171) it.</sub>

2022-07-31 12:00 UTC, chywang requested changes
would u pls add a readme w/ a simple tutorial?

2022-08-04 01:47 UTC, RheaRia commented
> would u pls add a readme w/ a simple tutorial?
Done.

2022-08-04 02:26 UTC, chywang approved these changes

2022-08-04 02:26 UTC, merged