Clip based i2t gen
alibaba/EasyNLP pull request #179
Opened 2022-08-07 15:46 UTC by zhuxiangru

2022-08-08 02:31 UTC, chywang requested changes

2022-08-08 02:31 UTC, chywang commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
这边run_appzoo_cli_local.sh命令为啥img_encoder=vqgan

2022-08-08 02:31 UTC, chywang commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
这边的问题也是

2022-08-08 02:31 UTC, chywang commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
+2

2022-08-08 11:06 UTC, zhuxiangru commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
已改。默认是vit编码器，不需要指定img_encoder。保留vqgan版本的（需要加enable_vqgan=True）

2022-08-08 11:07 UTC, zhuxiangru commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
已改。默认是vit编码器，不需要指定img_encoder。保留vqgan版本的（需要加enable_vqgan=True）

2022-08-08 11:07 UTC, zhuxiangru commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
已改。同上。

2022-08-08 11:08 UTC, zhuxiangru commented on examples/image2text_generation/run_appzoo_cli_local.sh
> +        img_encoder=vqgan
已改，同上。

2022-08-09 02:15 UTC, chywang approved these changes
lgtm

2022-08-09 02:15 UTC, merged